---
- name: Apply Kubernetes manifests using Ansible roles
  hosts: localhost
  become: false
  vars:
    kubeconfig_path: /home/administrator/.kube/config

  roles:
    - role: envSetup_role
    - role: patient_role
    - role: doctor_role
    - role: appointment_role
    - role: notification_role
    - role: monitoring_role
