- name: Apply rabbitmq
  environment:
    KUBECONFIG: /home/administrator/.kube/config
  command: kubectl apply -f {{ playbook_dir }}/Kubernetes/rabbitmq.yml

- name: Apply notification service
  environment:
    KUBECONFIG: /home/administrator/.kube/config
  command: kubectl apply -f {{ playbook_dir }}/Kubernetes/notification.yml